---
- name: "Get current EDA Decision Environments from the API"
  ansible.builtin.set_fact:
    eda_decision_environments_lookvar: "{{ query('ansible.platform.gateway_api', 'api/eda/v1/decision-environments/',
                                                 host=aap_hostname, oauth_token=aap_oauthtoken, verify_ssl=aap_validate_certs,
                                                 return_all=true, max_objects=query_eda_api_max_objects, errors='ignore')
                                        }}"
  no_log: "{{ eda_configuration_filetree_create_secure_logging }}"

- name: "Continue only if there has no errors with the previous API query"
  when:
    - eda_decision_environments_lookvar | length > 0
    - eda_decision_environments_lookvar | first | length > 0
  block:
    - name: "Create the output directory for EDA decision_environments: {{ output_path }}"
      ansible.builtin.file:
        path: "{{ output_path }}"
        state: directory
        mode: '0755'

    - name: "Add current EDA decision_environments to the eda_decision_environments.yaml output file in {{ output_path }}"
      ansible.builtin.template:
        src: "templates/eda_decision_environments.j2"
        dest: "{{ output_path }}/eda_decision_environments.yaml"
        mode: '0644'
      vars:
        current_eda_decision_environments_asset_value: "{{ eda_decision_environments_lookvar }}"
...
