---
- name: "Get current EDA Credentials from the API"
  ansible.builtin.set_fact:
    eda_credentials_lookvar: "{{ query('ansible.platform.gateway_api', 'api/eda/v1/eda-credentials/',
                                       host=aap_hostname, oauth_token=aap_oauthtoken, verify_ssl=aap_validate_certs,
                                       return_all=true, max_objects=query_eda_api_max_objects, errors='ignore')
                              }}"
  no_log: "{{ eda_configuration_filetree_create_secure_logging }}"

- name: "Continue only if there has no errors with the previous API query"
  when:
    - eda_credentials_lookvar | length > 0
    - eda_credentials_lookvar | first | length > 0
  block:
    - name: "Create the output directory for EDA credentials: {{ output_path }}"
      ansible.builtin.file:
        path: "{{ output_path }}"
        state: directory
        mode: '0755'

    - name: "Add current EDA credentials to the eda_credentials.yaml output file in {{ output_path }}"
      ansible.builtin.template:
        src: "templates/eda_credentials.j2"
        dest: "{{ output_path }}/eda_credentials.yaml"
        mode: '0644'
      vars:
        current_eda_credentials_asset_value: "{{ eda_credentials_lookvar }}"
...
